spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: company
  profiles:
    active: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: postgres
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8086