spring:
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASS}
    port: '587'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: customer
  profiles:
    active: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: *
path:
  app: http://localhost:8080/v1/auth/
