spring:
  cloud:
    config:
      name: user-service
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080

path:
  app: http://localhost:8080/v1/auth/



